// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: protobuf/user/protomsg.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_PASS Status = 0
	Status_FAIL Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "PASS",
		1: "FAIL",
	}
	Status_value = map[string]int32{
		"PASS": 0,
		"FAIL": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_user_protomsg_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_protobuf_user_protomsg_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_user_protomsg_proto_rawDescGZIP(), []int{0}
}

type CPU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brand   string `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cores   uint32 `protobuf:"varint,3,opt,name=cores,proto3" json:"cores,omitempty"`
	Age     *int64 `protobuf:"varint,4,opt,name=age,proto3,oneof" json:"age,omitempty"`
	Student Status `protobuf:"varint,5,opt,name=student,proto3,enum=protobuf.user.Status" json:"student,omitempty"`
}

func (x *CPU) Reset() {
	*x = CPU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_user_protomsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPU) ProtoMessage() {}

func (x *CPU) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_user_protomsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPU.ProtoReflect.Descriptor instead.
func (*CPU) Descriptor() ([]byte, []int) {
	return file_protobuf_user_protomsg_proto_rawDescGZIP(), []int{0}
}

func (x *CPU) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CPU) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CPU) GetCores() uint32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *CPU) GetAge() int64 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *CPU) GetStudent() Status {
	if x != nil {
		return x.Student
	}
	return Status_PASS
}

var File_protobuf_user_protomsg_proto protoreflect.FileDescriptor

var file_protobuf_user_protomsg_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x22, 0x95, 0x01,
	0x0a, 0x03, 0x43, 0x50, 0x55, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x15, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x48, 0x00, 0x52, 0x03, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x2f, 0x0a, 0x07,
	0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x07, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x42, 0x06, 0x0a,
	0x04, 0x5f, 0x61, 0x67, 0x65, 0x2a, 0x1c, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x08, 0x0a, 0x04, 0x50, 0x41, 0x53, 0x53, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49,
	0x4c, 0x10, 0x01, 0x42, 0x14, 0x5a, 0x12, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protobuf_user_protomsg_proto_rawDescOnce sync.Once
	file_protobuf_user_protomsg_proto_rawDescData = file_protobuf_user_protomsg_proto_rawDesc
)

func file_protobuf_user_protomsg_proto_rawDescGZIP() []byte {
	file_protobuf_user_protomsg_proto_rawDescOnce.Do(func() {
		file_protobuf_user_protomsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_user_protomsg_proto_rawDescData)
	})
	return file_protobuf_user_protomsg_proto_rawDescData
}

var file_protobuf_user_protomsg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_user_protomsg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_user_protomsg_proto_goTypes = []interface{}{
	(Status)(0), // 0: protobuf.user.Status
	(*CPU)(nil), // 1: protobuf.user.CPU
}
var file_protobuf_user_protomsg_proto_depIdxs = []int32{
	0, // 0: protobuf.user.CPU.student:type_name -> protobuf.user.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_user_protomsg_proto_init() }
func file_protobuf_user_protomsg_proto_init() {
	if File_protobuf_user_protomsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_user_protomsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CPU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protobuf_user_protomsg_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_user_protomsg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_user_protomsg_proto_goTypes,
		DependencyIndexes: file_protobuf_user_protomsg_proto_depIdxs,
		EnumInfos:         file_protobuf_user_protomsg_proto_enumTypes,
		MessageInfos:      file_protobuf_user_protomsg_proto_msgTypes,
	}.Build()
	File_protobuf_user_protomsg_proto = out.File
	file_protobuf_user_protomsg_proto_rawDesc = nil
	file_protobuf_user_protomsg_proto_goTypes = nil
	file_protobuf_user_protomsg_proto_depIdxs = nil
}
